# SPDX-License-Identifier: LGPL-3.0-or-later
# Copyright (C) 2020 Daniel Thompson
"""Shared manifest for applications that work well on a 240x240 display."""

manifest = (
    'apps/system/launcher.py',
    'apps/system/pager.py',
    'apps/system/software.py',
    'apps/system/settings.py',
    'apps/system/step_counter.py',
    'fonts/__init__.py',
    'fonts/clock.py',
    'fonts/clock_dual.py',
    'fonts/sans18.py',
    'fonts/sans24.py',
    'fonts/sans28.py',
    'fonts/sans36.py',
    'icons.py',
    'apps/system/steplogger.py',
    'widgets/__init__.py',
    'widgets/battery_meter.py',
    'widgets/clock.py',
    'widgets/notification_bar.py',
    'widgets/status_bar.py',
    'widgets/scroll_indicator.py',
    'widgets/button.py',
    'widgets/togglebutton.py',
    'widgets/checkbox.py',
    'widgets/gfxbutton.py',
    'widgets/slider.py',
    'widgets/spinner.py',
    'widgets/stopwatch.py',
    'widgets/confirmation_view.py',
    'appregistry.py',
)
