name: wasp-os binary distribution

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout files
      id:   checkout-files
      uses: actions/checkout@v4

    - name: Install arm-none-eabi-gcc
      id:   install-toolchain
      uses: carlosperate/arm-none-eabi-gcc-action@v1
      with:
          release: '13.3.Rel1'

    - name: Install packages
      id: install-packages
      run:  |
          sudo apt-get update
          sudo apt-get install -y python3-sphinx python3-cryptography python3-cbor graphviz
          sudo pip3 install recommonmark tomli

    - name: Update submodules
      id:   update-submodules
      run:  |
          make -j `nproc` submodules
    
    - name: Download softdevice
      id:   download-softdevice
      run:  |  
          make -j `nproc` softdevice

    - name: Build wasp-os binary distribution
      id:   binary-distribution
      run:  |
          make -j `nproc` VERSION=${{ github.sha }} dist
          mv ../wasp-os-${{ github.sha }}.tar.gz .

    - name: Build extra apps
      id:   apps
      run:  |
          make -j `nproc` apps

    - name: Upload full binary distribution
      id:   upload-binaries
      uses: actions/upload-artifact@v4
      with:
          name: wasp-os-${{ github.sha }}
          path: wasp-os-${{ github.sha }}.tar.gz

    - name: Upload pinetime binaries
      id:   upload-pinetime
      uses: actions/upload-artifact@v4
      with:
          name: pinetime-${{ github.sha }}
          path: build-pinetime

    - name: Upload Colmi P8 binaries
      id:   upload-p8
      uses: actions/upload-artifact@v4
      with:
          name: p8-${{ github.sha }}
          path: build-p8

    - name: Upload Senbono K9 binaries
      id:   upload-k9
      uses: actions/upload-artifact@v4
      with:
          name: k9-${{ github.sha }}
          path: build-k9

    - name: Upload extra apps binaries
      id:   upload-apps
      uses: actions/upload-artifact@v4
      with:
          name: apps-${{ github.sha }}
          path: |
            apps/*.mpy
            faces/*.mpy
